"""audit hash chain

Revision ID: f128de374959
Revises: 42de869b6fed
Create Date: 2026-07-18 16:12:30.848110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f128de374959'
down_revision: Union[str, None] = '42de869b6fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latest_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entry_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('prev_hash')

    op.drop_table('audit_chain_head')
    # ### end Alembic commands ###
