"""client org token budgets

Revision ID: bf77a10c66d1
Revises: f128de374959
Create Date: 2026-07-18 16:22:09.966561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf77a10c66d1'
down_revision: Union[str, None] = 'f128de374959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('token_count_reset_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.drop_column('token_count_reset_at')
        batch_op.drop_column('tokens_used_today')

    # ### end Alembic commands ###
